name: mphil-project
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - transformers
  - accelerate
  - pandas
  - scikit-learn
  - pyyaml
  - tqdm
  - pytest
  - matplotlib
